server:
  port: ${PORT:${SERVER_PORT:0}}

info:
  id: ${spring.application.name}

logging:
  level: debug

endpoints:
  shutdown:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/