server:
  port: ${PORT:8080}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

security:
  user:
    password: password

spring:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9999/uaa/user

zuul:
  routes:
    gft:
      path: /product/**
      serviceId: PRODUCT-SERVICE
    security:
      path: /security/**
      serviceId: SECURITY-SERVICE
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user